spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    # defined here the bootstrap servers are set both for the producer 
    # and the admin configurations
    # {$spring.kafka.boostrap-servers}
    # autowired configurations 
    bootstrap-servers: kaf1:9092,kaf2:9094,kaf3:9096
    topic: store-events
    template:
      default-topic: store-events
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      partitions: 3
      replicas: 3
      properties:
        retries: 10
        acks: 1
        security:
          protocol: SSL
        ssl.endpoint.identification.algorith:

    ssl:
      trust-store-location: file:../sslTools/secrets/kafka.producer.truststore.jks
      trust-store-password: confluentxx
      key-store-location: file:../sslTools/secrets/kafka.producer.keystore.jks
      key-store-password: confluentxx
    
    admin:
      autoCreate: true

---
